@startuml developer git workflow

partition Jira #LightYellow {
  (*) -down-> "Create Task"
  -down-> "Task in Progress"
  -down-> "Development Complete"
  -down-> "Link to Test Cases"
}

partition GitHub #LightGreen{
  partition develop #LightBlue{
    "Task in Progress" -down[dashed,#orange,thickness=8]-> "Branch off Develop"
    "Merge Feature into Develop" -[dashed,#orange,thickness=8]-> "Development Complete"
  }

  partition FF-123 #LightSeaGreen{
    "Branch off Develop" -[#blue,thickness=4]-> "Push the buttons"
    "Push the buttons" --> "Draft Pull Request"
    "Draft Pull Request" --> "Open Pull Request"

    if "New Branch for same Feature" then
      -down->[true] "Branch off FF-123"
    else
      -down->[false] "Branch off Develop"
    endif

    "Task in Progress" -[dashed,#orange,thickness=8]-> "Branch off FF-123"

    "Push the buttons" --> "Open Pull Request"

    if "PR Approved" then
      -->[true] "Merge Feature into Develop"
    else
      -->[false] "Push the buttons"
    endif

    "Merge Feature into Develop" -[#red,thickness=4]-> "Delete Branch"
  }

  partition FF-321 #Turquoise{
    "Branch off FF-123" -[#blue,thickness=4]-> "Push more buttons"

    "Push more buttons" --> "Draft PR"
    if "FF-123 PR Landed" then
      -->[true] "Open PR"
    else
      -->[false] "Push the buttons"
    endif

    "Delete Branch" -> "Merge Develop"
    "Merge Develop" --> "Open PR"
    "Open PR" --> "Merge Feature into Develop"

  }
}




@enduml
